version: '3'
services:
  excel-converter:
    platform: linux/amd64
    build: .
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    working_dir: /app
    command: python aspose_excel_to_pdf.py
    stdin_open: true
    tty: true
    
  spire-converter:
    platform: linux/amd64
    build: .
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    working_dir: /app
    command: python spirexls_excel_to_pdf.py
    stdin_open: true
    tty: true
